# Generated by Django 5.1.2 on 2024-10-22 14:00

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MEDIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('nombre', models.CharField(default='PLACEHOLDER NAME', max_length=50)),
                ('gmail', models.EmailField(default='PLACEHOLDER GMAIL', max_length=254)),
                ('contrasena', models.CharField(default='PLACEHOLDER PASSWORD', max_length=30)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PUBLICACION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='PLACEHOLDER TITLE', max_length=50)),
                ('descripcion', models.TextField(default='LOREMP PSIUM')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('archivos', models.ManyToManyField(related_name='files', to='models.media')),
                ('categoria', models.ManyToManyField(to='models.categoria')),
                ('portada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.media')),
                ('autor', models.ForeignKey(default='USUARIO', on_delete=django.db.models.deletion.CASCADE, to='models.usuario')),
            ],
        ),
    ]
