# Generated by Django 5.1.2 on 2024-10-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIGITOS_VERIFICADORES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=50)),
                ('dv', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='dv',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='dv',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='dv',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
