# Generated by Django 5.1 on 2024-08-16 14:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='archivos',
            field=models.ManyToManyField(related_name='files', to='models.media'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.ManyToManyField(to='models.categoria'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='descripcion',
            field=models.TextField(default='LOREMP PSIUM'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='portada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.media'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(default='PLACEHOLDER TITLE', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='PLACEHOLDER PASSWORD', max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='gmail',
            field=models.EmailField(default='PLACEHOLDER GMAIL', max_length=254),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='PLACEHOLDER NAME', max_length=50),
        ),
    ]
