# Generated by Django 4.2.12 on 2024-10-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_digitos_verificadores_media_dv_publicacion_dv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='dv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='digitos_verificadores',
            name='dv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='dv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='dv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dv',
            field=models.IntegerField(default=0),
        ),
    ]
