# Generated by Django 4.2.12 on 2024-10-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_categoria_dv_alter_digitos_verificadores_dv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='dv',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='digitos_verificadores',
            name='dv',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='media',
            name='dv',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='dv',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dv',
            field=models.IntegerField(default=1),
        ),
    ]
